/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ScheduleNowRouteImport } from './routes/schedule-now'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AreasNelspruitRouteImport } from './routes/areas.nelspruit'
import { Route as AreasNelspruitInsuranceClaimsRouteImport } from './routes/areas.nelspruit-insurance-claims'
import { Route as AreasNelspruitMaintenanceRouteImport } from './routes/areas.nelspruit-maintenance'
import { Route as AreasNelspruitNewInstallationsRouteImport } from './routes/areas.nelspruit-new-installations'
import { Route as AreasNelspruitRelocationsRouteImport } from './routes/areas.nelspruit-relocations'
import { Route as AreasNelspruitReplacementsRouteImport } from './routes/areas.nelspruit-replacements'
import { Route as AreasWhiteRiverRouteImport } from './routes/areas.white-river'
import { Route as AreasWhiteRiverInsuranceClaimsRouteImport } from './routes/areas.white-river-insurance-claims'
import { Route as AreasWhiteRiverMaintenanceRouteImport } from './routes/areas.white-river-maintenance'
import { Route as AreasWhiteRiverNewInstallationsRouteImport } from './routes/areas.white-river-new-installations'
import { Route as AreasWhiteRiverRelocationsRouteImport } from './routes/areas.white-river-relocations'
import { Route as AreasWhiteRiverReplacementsRouteImport } from './routes/areas.white-river-replacements'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesInsuranceClaimsRouteImport } from './routes/services.insurance-claims'
import { Route as ServicesMaintenanceRouteImport } from './routes/services.maintenance'
import { Route as ServicesNewInstallationsRouteImport } from './routes/services.new-installations'
import { Route as ServicesRelocationsRouteImport } from './routes/services.relocations'
import { Route as ServicesReplacementsRouteImport } from './routes/services.replacements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleNowRoute = ScheduleNowRouteImport.update({
  id: '/schedule-now',
  path: '/schedule-now',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasNelspruitRoute = AreasNelspruitRouteImport.update({
  id: '/areas/nelspruit',
  path: '/areas/nelspruit',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasNelspruitInsuranceClaimsRoute =
  AreasNelspruitInsuranceClaimsRouteImport.update({
    id: '/areas/nelspruit-insurance-claims',
    path: '/areas/nelspruit-insurance-claims',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasNelspruitMaintenanceRoute =
  AreasNelspruitMaintenanceRouteImport.update({
    id: '/areas/nelspruit-maintenance',
    path: '/areas/nelspruit-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasNelspruitNewInstallationsRoute =
  AreasNelspruitNewInstallationsRouteImport.update({
    id: '/areas/nelspruit-new-installations',
    path: '/areas/nelspruit-new-installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasNelspruitRelocationsRoute =
  AreasNelspruitRelocationsRouteImport.update({
    id: '/areas/nelspruit-relocations',
    path: '/areas/nelspruit-relocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasNelspruitReplacementsRoute =
  AreasNelspruitReplacementsRouteImport.update({
    id: '/areas/nelspruit-replacements',
    path: '/areas/nelspruit-replacements',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWhiteRiverRoute = AreasWhiteRiverRouteImport.update({
  id: '/areas/white-river',
  path: '/areas/white-river',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWhiteRiverInsuranceClaimsRoute =
  AreasWhiteRiverInsuranceClaimsRouteImport.update({
    id: '/areas/white-river-insurance-claims',
    path: '/areas/white-river-insurance-claims',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWhiteRiverMaintenanceRoute =
  AreasWhiteRiverMaintenanceRouteImport.update({
    id: '/areas/white-river-maintenance',
    path: '/areas/white-river-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWhiteRiverNewInstallationsRoute =
  AreasWhiteRiverNewInstallationsRouteImport.update({
    id: '/areas/white-river-new-installations',
    path: '/areas/white-river-new-installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWhiteRiverRelocationsRoute =
  AreasWhiteRiverRelocationsRouteImport.update({
    id: '/areas/white-river-relocations',
    path: '/areas/white-river-relocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasWhiteRiverReplacementsRoute =
  AreasWhiteRiverReplacementsRouteImport.update({
    id: '/areas/white-river-replacements',
    path: '/areas/white-river-replacements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInsuranceClaimsRoute = ServicesInsuranceClaimsRouteImport.update({
  id: '/services/insurance-claims',
  path: '/services/insurance-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/services/maintenance',
  path: '/services/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewInstallationsRoute =
  ServicesNewInstallationsRouteImport.update({
    id: '/services/new-installations',
    path: '/services/new-installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRelocationsRoute = ServicesRelocationsRouteImport.update({
  id: '/services/relocations',
  path: '/services/relocations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReplacementsRoute = ServicesReplacementsRouteImport.update({
  id: '/services/replacements',
  path: '/services/replacements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/schedule-now': typeof ScheduleNowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas/nelspruit': typeof AreasNelspruitRoute
  '/areas/nelspruit-insurance-claims': typeof AreasNelspruitInsuranceClaimsRoute
  '/areas/nelspruit-maintenance': typeof AreasNelspruitMaintenanceRoute
  '/areas/nelspruit-new-installations': typeof AreasNelspruitNewInstallationsRoute
  '/areas/nelspruit-relocations': typeof AreasNelspruitRelocationsRoute
  '/areas/nelspruit-replacements': typeof AreasNelspruitReplacementsRoute
  '/areas/white-river': typeof AreasWhiteRiverRoute
  '/areas/white-river-insurance-claims': typeof AreasWhiteRiverInsuranceClaimsRoute
  '/areas/white-river-maintenance': typeof AreasWhiteRiverMaintenanceRoute
  '/areas/white-river-new-installations': typeof AreasWhiteRiverNewInstallationsRoute
  '/areas/white-river-relocations': typeof AreasWhiteRiverRelocationsRoute
  '/areas/white-river-replacements': typeof AreasWhiteRiverReplacementsRoute
  '/services/insurance-claims': typeof ServicesInsuranceClaimsRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/new-installations': typeof ServicesNewInstallationsRoute
  '/services/relocations': typeof ServicesRelocationsRoute
  '/services/replacements': typeof ServicesReplacementsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/schedule-now': typeof ScheduleNowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas/nelspruit': typeof AreasNelspruitRoute
  '/areas/nelspruit-insurance-claims': typeof AreasNelspruitInsuranceClaimsRoute
  '/areas/nelspruit-maintenance': typeof AreasNelspruitMaintenanceRoute
  '/areas/nelspruit-new-installations': typeof AreasNelspruitNewInstallationsRoute
  '/areas/nelspruit-relocations': typeof AreasNelspruitRelocationsRoute
  '/areas/nelspruit-replacements': typeof AreasNelspruitReplacementsRoute
  '/areas/white-river': typeof AreasWhiteRiverRoute
  '/areas/white-river-insurance-claims': typeof AreasWhiteRiverInsuranceClaimsRoute
  '/areas/white-river-maintenance': typeof AreasWhiteRiverMaintenanceRoute
  '/areas/white-river-new-installations': typeof AreasWhiteRiverNewInstallationsRoute
  '/areas/white-river-relocations': typeof AreasWhiteRiverRelocationsRoute
  '/areas/white-river-replacements': typeof AreasWhiteRiverReplacementsRoute
  '/services/insurance-claims': typeof ServicesInsuranceClaimsRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/new-installations': typeof ServicesNewInstallationsRoute
  '/services/relocations': typeof ServicesRelocationsRoute
  '/services/replacements': typeof ServicesReplacementsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/schedule-now': typeof ScheduleNowRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/areas/nelspruit': typeof AreasNelspruitRoute
  '/areas/nelspruit-insurance-claims': typeof AreasNelspruitInsuranceClaimsRoute
  '/areas/nelspruit-maintenance': typeof AreasNelspruitMaintenanceRoute
  '/areas/nelspruit-new-installations': typeof AreasNelspruitNewInstallationsRoute
  '/areas/nelspruit-relocations': typeof AreasNelspruitRelocationsRoute
  '/areas/nelspruit-replacements': typeof AreasNelspruitReplacementsRoute
  '/areas/white-river': typeof AreasWhiteRiverRoute
  '/areas/white-river-insurance-claims': typeof AreasWhiteRiverInsuranceClaimsRoute
  '/areas/white-river-maintenance': typeof AreasWhiteRiverMaintenanceRoute
  '/areas/white-river-new-installations': typeof AreasWhiteRiverNewInstallationsRoute
  '/areas/white-river-relocations': typeof AreasWhiteRiverRelocationsRoute
  '/areas/white-river-replacements': typeof AreasWhiteRiverReplacementsRoute
  '/services/insurance-claims': typeof ServicesInsuranceClaimsRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/new-installations': typeof ServicesNewInstallationsRoute
  '/services/relocations': typeof ServicesRelocationsRoute
  '/services/replacements': typeof ServicesReplacementsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/contact-us'
    | '/gallery'
    | '/schedule-now'
    | '/sitemap.xml'
    | '/areas/nelspruit'
    | '/areas/nelspruit-insurance-claims'
    | '/areas/nelspruit-maintenance'
    | '/areas/nelspruit-new-installations'
    | '/areas/nelspruit-relocations'
    | '/areas/nelspruit-replacements'
    | '/areas/white-river'
    | '/areas/white-river-insurance-claims'
    | '/areas/white-river-maintenance'
    | '/areas/white-river-new-installations'
    | '/areas/white-river-relocations'
    | '/areas/white-river-replacements'
    | '/services/insurance-claims'
    | '/services/maintenance'
    | '/services/new-installations'
    | '/services/relocations'
    | '/services/replacements'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/blog'
    | '/contact-us'
    | '/gallery'
    | '/schedule-now'
    | '/sitemap.xml'
    | '/areas/nelspruit'
    | '/areas/nelspruit-insurance-claims'
    | '/areas/nelspruit-maintenance'
    | '/areas/nelspruit-new-installations'
    | '/areas/nelspruit-relocations'
    | '/areas/nelspruit-replacements'
    | '/areas/white-river'
    | '/areas/white-river-insurance-claims'
    | '/areas/white-river-maintenance'
    | '/areas/white-river-new-installations'
    | '/areas/white-river-relocations'
    | '/areas/white-river-replacements'
    | '/services/insurance-claims'
    | '/services/maintenance'
    | '/services/new-installations'
    | '/services/relocations'
    | '/services/replacements'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blog'
    | '/contact-us'
    | '/gallery'
    | '/schedule-now'
    | '/sitemap.xml'
    | '/areas/nelspruit'
    | '/areas/nelspruit-insurance-claims'
    | '/areas/nelspruit-maintenance'
    | '/areas/nelspruit-new-installations'
    | '/areas/nelspruit-relocations'
    | '/areas/nelspruit-replacements'
    | '/areas/white-river'
    | '/areas/white-river-insurance-claims'
    | '/areas/white-river-maintenance'
    | '/areas/white-river-new-installations'
    | '/areas/white-river-relocations'
    | '/areas/white-river-replacements'
    | '/services/insurance-claims'
    | '/services/maintenance'
    | '/services/new-installations'
    | '/services/relocations'
    | '/services/replacements'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRoute
  ContactUsRoute: typeof ContactUsRoute
  GalleryRoute: typeof GalleryRoute
  ScheduleNowRoute: typeof ScheduleNowRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AreasNelspruitRoute: typeof AreasNelspruitRoute
  AreasNelspruitInsuranceClaimsRoute: typeof AreasNelspruitInsuranceClaimsRoute
  AreasNelspruitMaintenanceRoute: typeof AreasNelspruitMaintenanceRoute
  AreasNelspruitNewInstallationsRoute: typeof AreasNelspruitNewInstallationsRoute
  AreasNelspruitRelocationsRoute: typeof AreasNelspruitRelocationsRoute
  AreasNelspruitReplacementsRoute: typeof AreasNelspruitReplacementsRoute
  AreasWhiteRiverRoute: typeof AreasWhiteRiverRoute
  AreasWhiteRiverInsuranceClaimsRoute: typeof AreasWhiteRiverInsuranceClaimsRoute
  AreasWhiteRiverMaintenanceRoute: typeof AreasWhiteRiverMaintenanceRoute
  AreasWhiteRiverNewInstallationsRoute: typeof AreasWhiteRiverNewInstallationsRoute
  AreasWhiteRiverRelocationsRoute: typeof AreasWhiteRiverRelocationsRoute
  AreasWhiteRiverReplacementsRoute: typeof AreasWhiteRiverReplacementsRoute
  ServicesInsuranceClaimsRoute: typeof ServicesInsuranceClaimsRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesNewInstallationsRoute: typeof ServicesNewInstallationsRoute
  ServicesRelocationsRoute: typeof ServicesRelocationsRoute
  ServicesReplacementsRoute: typeof ServicesReplacementsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-now': {
      id: '/schedule-now'
      path: '/schedule-now'
      fullPath: '/schedule-now'
      preLoaderRoute: typeof ScheduleNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit': {
      id: '/areas/nelspruit'
      path: '/areas/nelspruit'
      fullPath: '/areas/nelspruit'
      preLoaderRoute: typeof AreasNelspruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit-insurance-claims': {
      id: '/areas/nelspruit-insurance-claims'
      path: '/areas/nelspruit-insurance-claims'
      fullPath: '/areas/nelspruit-insurance-claims'
      preLoaderRoute: typeof AreasNelspruitInsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit-maintenance': {
      id: '/areas/nelspruit-maintenance'
      path: '/areas/nelspruit-maintenance'
      fullPath: '/areas/nelspruit-maintenance'
      preLoaderRoute: typeof AreasNelspruitMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit-new-installations': {
      id: '/areas/nelspruit-new-installations'
      path: '/areas/nelspruit-new-installations'
      fullPath: '/areas/nelspruit-new-installations'
      preLoaderRoute: typeof AreasNelspruitNewInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit-relocations': {
      id: '/areas/nelspruit-relocations'
      path: '/areas/nelspruit-relocations'
      fullPath: '/areas/nelspruit-relocations'
      preLoaderRoute: typeof AreasNelspruitRelocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/nelspruit-replacements': {
      id: '/areas/nelspruit-replacements'
      path: '/areas/nelspruit-replacements'
      fullPath: '/areas/nelspruit-replacements'
      preLoaderRoute: typeof AreasNelspruitReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river': {
      id: '/areas/white-river'
      path: '/areas/white-river'
      fullPath: '/areas/white-river'
      preLoaderRoute: typeof AreasWhiteRiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river-insurance-claims': {
      id: '/areas/white-river-insurance-claims'
      path: '/areas/white-river-insurance-claims'
      fullPath: '/areas/white-river-insurance-claims'
      preLoaderRoute: typeof AreasWhiteRiverInsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river-maintenance': {
      id: '/areas/white-river-maintenance'
      path: '/areas/white-river-maintenance'
      fullPath: '/areas/white-river-maintenance'
      preLoaderRoute: typeof AreasWhiteRiverMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river-new-installations': {
      id: '/areas/white-river-new-installations'
      path: '/areas/white-river-new-installations'
      fullPath: '/areas/white-river-new-installations'
      preLoaderRoute: typeof AreasWhiteRiverNewInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river-relocations': {
      id: '/areas/white-river-relocations'
      path: '/areas/white-river-relocations'
      fullPath: '/areas/white-river-relocations'
      preLoaderRoute: typeof AreasWhiteRiverRelocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/white-river-replacements': {
      id: '/areas/white-river-replacements'
      path: '/areas/white-river-replacements'
      fullPath: '/areas/white-river-replacements'
      preLoaderRoute: typeof AreasWhiteRiverReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/insurance-claims': {
      id: '/services/insurance-claims'
      path: '/services/insurance-claims'
      fullPath: '/services/insurance-claims'
      preLoaderRoute: typeof ServicesInsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/services/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new-installations': {
      id: '/services/new-installations'
      path: '/services/new-installations'
      fullPath: '/services/new-installations'
      preLoaderRoute: typeof ServicesNewInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/relocations': {
      id: '/services/relocations'
      path: '/services/relocations'
      fullPath: '/services/relocations'
      preLoaderRoute: typeof ServicesRelocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/replacements': {
      id: '/services/replacements'
      path: '/services/replacements'
      fullPath: '/services/replacements'
      preLoaderRoute: typeof ServicesReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRoute,
  ContactUsRoute: ContactUsRoute,
  GalleryRoute: GalleryRoute,
  ScheduleNowRoute: ScheduleNowRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AreasNelspruitRoute: AreasNelspruitRoute,
  AreasNelspruitInsuranceClaimsRoute: AreasNelspruitInsuranceClaimsRoute,
  AreasNelspruitMaintenanceRoute: AreasNelspruitMaintenanceRoute,
  AreasNelspruitNewInstallationsRoute: AreasNelspruitNewInstallationsRoute,
  AreasNelspruitRelocationsRoute: AreasNelspruitRelocationsRoute,
  AreasNelspruitReplacementsRoute: AreasNelspruitReplacementsRoute,
  AreasWhiteRiverRoute: AreasWhiteRiverRoute,
  AreasWhiteRiverInsuranceClaimsRoute: AreasWhiteRiverInsuranceClaimsRoute,
  AreasWhiteRiverMaintenanceRoute: AreasWhiteRiverMaintenanceRoute,
  AreasWhiteRiverNewInstallationsRoute: AreasWhiteRiverNewInstallationsRoute,
  AreasWhiteRiverRelocationsRoute: AreasWhiteRiverRelocationsRoute,
  AreasWhiteRiverReplacementsRoute: AreasWhiteRiverReplacementsRoute,
  ServicesInsuranceClaimsRoute: ServicesInsuranceClaimsRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesNewInstallationsRoute: ServicesNewInstallationsRoute,
  ServicesRelocationsRoute: ServicesRelocationsRoute,
  ServicesReplacementsRoute: ServicesReplacementsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
