/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogChoosingAnEmmGradeRouteImport } from './routes/blog/choosing-an-emm-grade'
import { Route as BlogReadingACertificateOfAnalysisRouteImport } from './routes/blog/reading-a-certificate-of-analysis'
import { Route as BlogWhySeleniumFreeMattersRouteImport } from './routes/blog/why-selenium-free-matters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogChoosingAnEmmGradeRoute = BlogChoosingAnEmmGradeRouteImport.update({
  id: '/blog/choosing-an-emm-grade',
  path: '/blog/choosing-an-emm-grade',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogReadingACertificateOfAnalysisRoute =
  BlogReadingACertificateOfAnalysisRouteImport.update({
    id: '/blog/reading-a-certificate-of-analysis',
    path: '/blog/reading-a-certificate-of-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhySeleniumFreeMattersRoute =
  BlogWhySeleniumFreeMattersRouteImport.update({
    id: '/blog/why-selenium-free-matters',
    path: '/blog/why-selenium-free-matters',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/blog/choosing-an-emm-grade': typeof BlogChoosingAnEmmGradeRoute
  '/blog/reading-a-certificate-of-analysis': typeof BlogReadingACertificateOfAnalysisRoute
  '/blog/why-selenium-free-matters': typeof BlogWhySeleniumFreeMattersRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/blog/choosing-an-emm-grade': typeof BlogChoosingAnEmmGradeRoute
  '/blog/reading-a-certificate-of-analysis': typeof BlogReadingACertificateOfAnalysisRoute
  '/blog/why-selenium-free-matters': typeof BlogWhySeleniumFreeMattersRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/blog/choosing-an-emm-grade': typeof BlogChoosingAnEmmGradeRoute
  '/blog/reading-a-certificate-of-analysis': typeof BlogReadingACertificateOfAnalysisRoute
  '/blog/why-selenium-free-matters': typeof BlogWhySeleniumFreeMattersRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/blog/choosing-an-emm-grade'
    | '/blog/reading-a-certificate-of-analysis'
    | '/blog/why-selenium-free-matters'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/blog/choosing-an-emm-grade'
    | '/blog/reading-a-certificate-of-analysis'
    | '/blog/why-selenium-free-matters'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/blog/choosing-an-emm-grade'
    | '/blog/reading-a-certificate-of-analysis'
    | '/blog/why-selenium-free-matters'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  BlogChoosingAnEmmGradeRoute: typeof BlogChoosingAnEmmGradeRoute
  BlogReadingACertificateOfAnalysisRoute: typeof BlogReadingACertificateOfAnalysisRoute
  BlogWhySeleniumFreeMattersRoute: typeof BlogWhySeleniumFreeMattersRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/choosing-an-emm-grade': {
      id: '/blog/choosing-an-emm-grade'
      path: '/blog/choosing-an-emm-grade'
      fullPath: '/blog/choosing-an-emm-grade'
      preLoaderRoute: typeof BlogChoosingAnEmmGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reading-a-certificate-of-analysis': {
      id: '/blog/reading-a-certificate-of-analysis'
      path: '/blog/reading-a-certificate-of-analysis'
      fullPath: '/blog/reading-a-certificate-of-analysis'
      preLoaderRoute: typeof BlogReadingACertificateOfAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-selenium-free-matters': {
      id: '/blog/why-selenium-free-matters'
      path: '/blog/why-selenium-free-matters'
      fullPath: '/blog/why-selenium-free-matters'
      preLoaderRoute: typeof BlogWhySeleniumFreeMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  GalleryRoute: GalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  BlogChoosingAnEmmGradeRoute: BlogChoosingAnEmmGradeRoute,
  BlogReadingACertificateOfAnalysisRoute:
    BlogReadingACertificateOfAnalysisRoute,
  BlogWhySeleniumFreeMattersRoute: BlogWhySeleniumFreeMattersRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
